INSERT OR REPLACE INTO "CARD" VALUES (
    $ID, -- INTEGER
    $NAME, -- TEXT
    $TEXT_ID, -- INTEGER
    $ARTWORK, -- TEXT
    $RARITY, -- INTEGER
    $RANGE, -- INTEGER
    $COST, -- INTEGER
    $AFFECTION, -- INTEGER
    $EMOTION_LIMIT, -- INTEGER
    $SCRIPT, -- TEXT
    $SCRIPT_DESC, -- TEXT
    $CHAPTER, -- INTEGER
    $SPECIAL_EFFECT, -- TEXT
    $SKIN_CHANGE, -- TEXT
    $SKIN_CHANGE_TYPE, -- INTEGER
    $SKIN_HEIGHT, -- INTEGER
    $MAP_CHANGE, -- TEXT
    $PRIORITY, -- INTEGER
    $PRIORITY_SCRIPT, -- TEXT
    $CATEGORY, -- INTEGER
    $MAX_COOLTIME_FOR_EGO, -- INTEGER
    $MAX_NUM -- INTEGER
);
