INSERT OR REPLACE INTO "CARD_BEHAVIOUR" VALUES (
    $ID, -- INTEGER
    $INDEX, -- INTEGER
    $MIN, -- INTEGER
    $DICE, -- INTEGER
    $TYPE, -- INTEGER
    $DETAIL, -- INTEGER
    $MOTION, -- INTEGER
    $MOTION_DEFAULT, -- INTEGER
    $EFFECT_RES, -- TEXT
    $SCRIPT, -- TEXT
    $ACTION_SCRIPT, -- TEXT
    $DESC -- TEXT
);
