-- バトル ページ情報で使用するテーブル群を再構築するクエリです。

-- バトル ページ テーブル:
--   1レコードで単一のバトル ページ情報を定義します。
DROP TABLE IF EXISTS "CARD";
CREATE TABLE "CARD" (
    "ID" INTEGER NOT NULL,
    "NAME" TEXT NOT NULL,
    "TEXT_ID" INTEGER NOT NULL,
    "ARTWORK" TEXT NOT NULL,
    "RARITY" INTEGER NOT NULL,
    "RANGE" INTEGER NOT NULL,
    "COST" INTEGER NOT NULL,
    "AFFECTION" INTEGER NOT NULL,
    "EMOTION_LIMIT" INTEGER NOT NULL,
    "SCRIPT" TEXT NOT NULL,
    "SCRIPT_DESC" TEXT NOT NULL,
    "CHAPTER" INTEGER NOT NULL,
    "SPECIAL_EFFECT" TEXT NOT NULL,
    "SKIN_CHANGE" TEXT NOT NULL,
    "SKIN_CHANGE_TYPE" INTEGER NOT NULL,
    "SKIN_HEIGHT" INTEGER NOT NULL,
    "MAP_CHANGE" TEXT NOT NULL,
    "PRIORITY" INTEGER NOT NULL,
    "PRIORITY_SCRIPT" TEXT NOT NULL,
    "CATEGORY" INTEGER NOT NULL,
    "MAX_COOLTIME_FOR_EGO" INTEGER NOT NULL,
    "MAX_NUM" INTEGER NOT NULL,
    PRIMARY KEY("ID")
);

-- バトル ページ オプション テーブル:
--   バトル ページに付与するオプションを定義します。
--   "CARD"."ID" と "CARD_OPTION"."CARD_ID" で結合してどのバトルページに対する定義なのかを表し、
--   "CARD_OPTION"."INDEX" の値で単一のバトル ページに対して複数のオプションを定義することができます。
DROP TABLE IF EXISTS "CARD_OPTION";
CREATE TABLE "CARD_OPTION" (
    "CARD_ID" INTEGER NOT NULL,
    "INDEX" INTEGER NOT NULL,
    "VALUE" INTEGER NOT NULL,
    PRIMARY KEY("CARD_ID", "INDEX")
);

-- バトル ページ ヘルプ キーワード テーブル:
--   バトル ページに表示するヘルプ メッセージのキーワードを定義します。
DROP TABLE IF EXISTS "CARD_KEYWORD";
CREATE TABLE "CARD_KEYWORD" (
    "CARD_ID" INTEGER NOT NULL,
    "INDEX" INTEGER NOT NULL,
    "VALUE" TEXT NOT NULL,
    PRIMARY KEY("CARD_ID", "INDEX")
);

-- バトル ページ ダイス振る舞いテーブル
--   バトル ページが持つバトル ダイスの振る舞いを定義します。
DROP TABLE IF EXISTS "CARD_BEHAVIOUR";
CREATE TABLE "CARD_BEHAVIOUR" (
    "CARD_ID" INTEGER NOT NULL,
    "INDEX" INTEGER NOT NULL,
    "MIN" INTEGER NOT NULL,
    "DICE" INTEGER NOT NULL,
    "TYPE" INTEGER NOT NULL,
    "DETAIL" INTEGER NOT NULL,
    "MOTION" INTEGER NOT NULL,
    "MOTION_DEFAULT" INTEGER NOT NULL,
    "EFFECT_RES" TEXT NOT NULL,
    "SCRIPT" TEXT NOT NULL,
    "ACTION_SCRIPT" TEXT NOT NULL,
    "DESC" TEXT NOT NULL,
    PRIMARY KEY("CARD_ID", "INDEX")
);
