SELECT
	C.ID,
	CASE WHEN "DESC".LOCALIZED_NAME IS NULL
		THEN C.NAME
		ELSE "DESC".LOCALIZED_NAME
		END "NAME",
	C.ARTWORK,
	C.RARITY,
	RARITY.LOCALIZED_NAME RARITY_NAME,
	C.RANGE,
	"RANGE".LOCALIZED_NAME RANGE_NAME,
	C.COST,
	C.CHAPTER
FROM "CARD" C
LEFT OUTER JOIN CARD_DESC "DESC"
	ON (C.TEXT_ID = -1 AND C.ID = "DESC".ID)
	OR (C.TEXT_ID <> -1 AND C.TEXT_ID = "DESC".ID)
LEFT OUTER JOIN ENUM_RARITY_DESC RARITY
	ON C.RARITY = RARITY.VALUE
LEFT OUTER JOIN ENUM_RANGE_DESC "RANGE"
	ON C.RANGE = "RANGE".VALUE
