//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuinaDataCatalog.RuinaDBSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuinaDataCatalog.RuinaDBSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   -- 列挙値の説明テーブル群を再構築し、レコードを追加するクエリです。
        ///
        ///-- レアリティ説明テーブル
        ///DROP TABLE IF EXISTS &quot;ENUM_RARITY_DESC&quot;;
        ///CREATE TABLE IF NOT EXISTS &quot;ENUM_RARITY_DESC&quot; (
        ///	&quot;VALUE&quot; INTEGER NOT NULL,
        ///	&quot;LOCALIZED_NAME&quot; TEXT NOT NULL,
        ///	PRIMARY KEY (&quot;VALUE&quot;)
        ///);
        ///INSERT INTO &quot;ENUM_RARITY_DESC&quot; VALUES
        ///	(0, &apos;普及&apos;),
        ///	(1, &apos;高級&apos;),
        ///	(2, &apos;限定&apos;),
        ///	(3, &apos;芸術&apos;);
        ///
        ///-- バトルページ攻撃範囲説明テーブル
        ///DROP TABLE IF EXISTS &quot;ENUM_RANGE_DESC&quot;;
        ///CREATE TABLE IF NOT EXISTS &quot;ENUM_RANGE_DESC&quot; (
        ///	&quot;VALUE&quot; INTEGER NOT NULL,
        ///	&quot;LOCALIZED_NAME&quot; TEXT NOT NULL,
        ///	PRIMARY KE [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RebuildAndInsertEnumTables {
            get {
                return ResourceManager.GetString("RebuildAndInsertEnumTables", resourceCulture);
            }
        }
    }
}
